const express = require('express')
const router = express.Router()

// ======================
// DO NOT EDIT THIS FILE
// This is a copy of the prod file. The prod version is the source of truth
// ======================

const redirects = {
  // Used on landing page
  '/plans': '/app/settings/2',

  // Not used anymore, legacy for external incoming links
  '/pricing': '/plans',
  '/account': '/app',
  '/account/pricing': '/plans',
  '/account/upgrade': '/plans',

  // Routes to Vue app
  '/sign-up': '/app/signup',
  '/login': '/app/signin',

  '/': '/app'
}

Object.keys(redirects).forEach((key) => {
  router.get(key, (req, res) => {
    res.redirect(redirects[key])
  })
})

// Team invitation from email links
router.get('/invite/team', (req, res) => {
  const matched = req.url.match(/\?.+$/)
  const params = matched && matched[0]
  res.redirect(`/app/team/invite${params}`)
})

// Reset password and Sign in from email links
// remove them if the link in email change
router.get('/login/confirm', (req, res) => {
  if (req.query.action === 'ChangePassword') {
    res.redirect(`/app/reset?id=${req.query.id}`)
  } else {
    res.redirect(`/app/signin?signinId=${req.query.id}`)
  }
})

module.exports = router
